title: 我们一起BUIDL吧!
description: 最性感的区块链媒体
author: 区块链媒体
github: www.buidl.tv
about:  BUIDL采用谈话、聊天、访谈等形式，轻松愉快，由浅入深的为大家介绍区块链技术，及其应用案例，以及有代表性的加密货币，区块链项目，有趣的DAPP等，并有投资专家为大家解读市场走势。这是一个美好而又富有机遇和挑战的时代，让我们一起做这个时代的弄潮儿！！！
disqus_shortname: bbihyq
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/logo.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:


share:
  twitter_username: bbihyq
  fb_appid: 1749788565247320

urls:
    - text: 关于我们
      url: /about/
    - text: 项目介绍
      url: /projects/
    - text: RSS订阅
      url: /feed.xml

url: "https://buidl.tv/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
