title: 宇清Talks - 商业、投资、新知
description: 何宇清老师的个人频道，在这里分享创业投资、个人成长、读书和认知科学
author: 何宇清
github: www.airwe.com
about:  Hi，我是六哥，创业十年的老韭菜，爱分享，爱折腾，也爱交朋友。期待与你相识。
disqus_shortname: bbihyq
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/he.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:


share:
  twitter_username: bbihyq
  fb_appid: 1749788565247320

urls:
    - text: 关于
      url: /about/
    - text: 资源
      url: /projects/
    - text: 微博
      url: https://weibo.com/heyuqing
    - text: RSS订阅
      url: /feed.xml

url: "https://www.aire.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
