title: 何宇清
description: 何宇清的个人博客
author: heyuqing
github: www.airwe.com
about:  何宇清，网称六哥，知名科技创业博客《商业不靠谱》的发起人、主编，区块链基金共石资本合伙人，BUIDL实验室创办人，活跃的互联网实践者和营销专家，中科院创业导师。屡败屡战的连续创业者，开过广告公司，折腾过电商，做过女性社交购物APP，创业前任职于全球最大的广告集团奥美、互联网社区门户大旗网。爱分享，爱折腾，也爱打太极拳。六哥是陈式太极拳第十二代传人，欢迎与他交流切磋。
disqus_shortname: bbihyq
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/logo.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:


share:
  twitter_username: bbihyq
  fb_appid: 1749788565247320

urls:
    - text: 关于
      url: /about/
    - text: 项目介绍
      url: /projects/
    - text: RSS订阅
      url: /feed.xml

url: "https://buidl.tv/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
