title: 何宇清的博客
description: 分享创业投资、个人成长、读书和认知科学
author: 何宇清
github: www.airwe.com
about:  Hi，我是六哥，创业十年的老韭菜，知名科技创业博客《商业不靠谱》的发起人，开过广告公司，折腾过电商，做过女性社交购物APP，创业前任职于全球最大的广告集团奥美、互联网社区门户大旗网。爱分享，爱折腾，也爱打太极拳。六哥是陈式太极拳第十二代传人，欢迎与他交流切磋。
disqus_shortname: bbihyq
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/he.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:


share:
  twitter_username: bbihyq
  fb_appid: 1749788565247320

urls:
    - text: 关于
      url: /about/
    - text: 项目介绍
      url: /projects/
    - text: RSS订阅
      url: /feed.xml

url: "https://buidl.tv/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
